# Generated by Django 4.2.5 on 2023-11-02 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingDetail',
            fields=[
                ('order_no', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('building', models.CharField(max_length=30)),
                ('add1', models.CharField(max_length=30)),
                ('add2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Delhi', 'Delhi')], max_length=30)),
                ('pincode', models.IntegerField()),
                ('order_date', models.DateField()),
                ('total_amount', models.FloatField()),
            ],
            options={
                'db_table': 'bill_details',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('delivery_status', models.CharField(max_length=30)),
                ('delivery_date', models.DateField()),
                ('bill_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetsApp.billingdetail')),
            ],
            options={
                'db_table': 'order_product',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('available', models.CharField(choices=[('Not Available', 'Not Available'), ('Available', 'Available')], max_length=30)),
                ('image', models.ImageField(upload_to='media')),
                ('slug', models.SlugField(default='')),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(max_length=30)),
                ('payment_date_time', models.DateTimeField(auto_now_add=True)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetsApp.orderproduct')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetsApp.pet'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetsApp.customers')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetsApp.pet')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.AddField(
            model_name='billingdetail',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PetsApp.customers'),
        ),
    ]
