# Generated by Django 4.2.5 on 2023-11-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='id',
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default='', max_length=150, primary_key=True, serialize=False),
        ),
    ]
