# Generated by Django 4.2.5 on 2023-11-06 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PetsApp', '0002_remove_payment_id_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order_product',
        ),
        migrations.AddField(
            model_name='payment',
            name='order_no',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='PetsApp.billingdetail'),
        ),
    ]
